In [1]:
from database.database import Table_wall_social_media,engine,metadata
import pandas as pd
table_object = Table_wall_social_media
conn = engine.connect()
df = pd.read_sql_query(
    '''
SELECT *
FROM wall_social_media
WHERE DATE_PART('year', date) IN (2023,2022,2021)'''
,con=conn
)
df

,id,src,hash,views,likes,reposts,comment_numb,date,owner_id,date_added
0,12501,science_technology,YmjjNLw1F2bgJR14oYbacV5WCOU,1144848.0,18707.0,4810.0,0.0,2023-05-03 12:35:47,-31976785,2023-07-30
1,12502,science_technology,NoS18bhBiRiE-4HnyMsfldU_RB8,22483.0,69.0,34.0,0.0,2023-07-30 18:24:00,-31976785,2023-07-30
2,12503,science_technology,6pJxK88KQJx-0e_-larxVH6ppxE,21076.0,86.0,38.0,0.0,2023-07-30 17:54:00,-31976785,2023-07-30
3,12504,science_technology,P8Oa1W0EKcR0bWxu3An4Q5ZewZU,17065.0,39.0,37.0,0.0,2023-07-30 17:38:00,-31976785,2023-07-30
4,12505,science_technology,-Ev-gvqpisUB_NlyfedHVg5BGgo,33033.0,464.0,343.0,0.0,2023-07-30 17:16:02,-31976785,2023-07-30
...,...,...,...,...,...,...,...,...,...,...
11833,24335,science_technology,wR9XZ1rvQgwylILr7nPi3QjidmM,374038.0,4731.0,776.0,406.0,2021-01-01 14:12:00,-31976785,2023-07-30
11834,24336,science_technology,rUAlAgDhDp7qB9ix1bHaMK6xgVs,527669.0,6581.0,2228.0,208.0,2021-01-01 12:12:00,-31976785,2023-07-30
11835,24337,science_technology,PJ8-6OAi9VHcDHPvo4PFRQYEI8E,341437.0,1958.0,108.0,88.0,2021-01-01 10:12:00,-31976785,2023-07-30
11836,24338,science_technology,KJSEcfcXQrgW4q-Ft9Uad4milB4,176042.0,1839.0,259.0,73.0,2021-01-01 08:12:00,-31976785,2023-07-30
11837,24339,science_technology,PB5Fe6oGERfgIUpWLR-77RqPGFw,182870.0,3235.0,97.0,48.0,2021-01-01 00:12:00,-31976785,2023-07-30